### ISSUE TITLE
only can you help to find data to run your code 

### ISSUE THREAD

**Issue by Sandy4321** [shuhantao/KDD2019-Challenge#1]
great code thanks
only can you help to find data to run your code 
KDD Cup 2019 AutoML for Temporal Relational Data
https://codalab.lri.fr/competitions/559

**Comment by HantaoShu** [comment]
https://drive.google.com/open?id=130xSScJq2S63Yz4kf1xb3O3J-4AeN6_S
this is the data for kdd cup 2019

**Comment by Sandy4321** [comment]
great , thanks for generous present 
by the way 
there are 2 links for data descriptions
https://www.4paradigm.com/competition/kddcup2019#data
and
https://codalab.lri.fr/competitions/559#learn_the_details-data

is it enough or more details needed?

**Comment by HantaoShu** [comment]
you also need a start-kit docker, but I can't find this docker, instead I upload  ingestion.py, which is not the original code provided by the KDD challenge. Hope this code can help you to run our program.

**Comment by Sandy4321** [comment]
great thanks
I see
https://github.com/HantaoShu/KDD2019-Challenge/blob/final_submit_code/ingestion.py

then I need run first 
https://github.com/HantaoShu/KDD2019-Challenge/blob/final_submit_code/preprocess.py
and after 
https://github.com/HantaoShu/KDD2019-Challenge/blob/final_submit_code/model.py

this file 
ingestion.py
will be used somehow automatically ? meaning called by one of  your files?
but I see no file was changed after you upload ingestion.py?

and only what I need to install is
os.system("pip3 install lightgbm")
os.system("pip3 install joblib")
os.system('pip3 install pandas==0.24.2')
os.system("pip3 install future")
os.system("pip3 install networkx")
os.system("pip3 install tqdm")
os.system("pip3 install holidays")

am I right?

**Comment by HantaoShu** [comment]
ingestion.py can automatically train the model and predict.
You only need to install the above packages, and these packages will be automatically installed when you run the code.

**Comment by Sandy4321** [comment]
I see
so I Need only to run this file
ingestion.py
and rest will be done automatically?

**Comment by HantaoShu** [comment]
Yes, I think so

**Comment by Sandy4321** [comment]
super
and will it work for windows?

**Comment by HantaoShu** [comment]
It should be, but we test on linux

**Comment by Sandy4321** [comment]
get error
AutoML for Temporal Relational Data 2019\data mar23\code updated file added\KDD2019-Challenge-final_submit_code\ingestion.py", line 215, in main
  with timer.time_limit('Initialization'):
File "C:\Users\User\Anaconda3\Lib\contextlib.py", line 112, in __enter__
  return next(self.gen)
File "d:\Sander\AutoML for Temporal Relational Data 2019\data mar23\code updated file added\KDD2019-Challenge-final_submit_code\ingestion.py", line 86, in time_limit
  signal.signal(signal.SIGALRM, signal_handler)

builtins.AttributeError: module 'signal' has no attribute 'SIGALRM'

may you help to fix it?

**Comment by Sandy4321** [comment]
https://stackoverflow.com/questions/52779920/why-is-signal-sigalrm-not-working-in-python-on-windows

**Comment by HantaoShu** [comment]
Sorry, in our experiment, we haven't got this error. Maybe you should try to get the docker, and try to run the code in the competition environment again

**Comment by Sandy4321** [comment]
no, the problem that I do use windows and this functionality is not working for windows
but it is not something important 
may be just remove this : just not to set delay to open file?
you know the code, can you do it?
https://docs.python.org/2/library/signal.html
17.4.1. Example
Here is a minimal example program. It uses the alarm() function to limit the time spent waiting to open a file; this is useful if the file is for a serial device that may not be turned on, which would normally cause the os.open() to hang indefinitely. The solution is to set a 5-second alarm before opening the file; if the operation takes too long, the alarm signal will be sent, and the handler raises an exception.

import signal, os

def handler(signum, frame):
    print 'Signal handler called with signal', signum
    raise IOError("Couldn't open device!")

# Set the signal handler and a 5-second alarm
signal.signal(signal.SIGALRM, handler)
signal.alarm(5) 

![image](https://user-images.githubusercontent.com/11426119/77346962-77322980-6d0d-11ea-9f6c-68aaec8b8656.png)
